export const bgFredLogo = require('./bg-fredLogo.png')
export const JumpingGirl = require('./JumpingGirl.png')
export const fredmindWhiteLogo = require('./LOGOFREDMINDWhite.png')
export const fredmindBlackLogo = require('./LOGOFREDMINDBlack.png')
export const ApplyboardLogo = require('./blue_logo.png')
export const KcOverseasLogo = require('./kcpng.png')
export const VisaLogo = require('./visalogo.png')